project:
  type: website
  output-dir: ../docs
website:
  title: "APL Study Group"
  navbar:
    right:
      - about.ipynb
      - icon: github
        href: https://github.com/fastai/apl-study
      - icon: twitter
        href: https://twitter.com/fastdotai/
format:
  html:
    theme: cerulean
    css: styles.css
    mainfont: SAX2
